title: kvnchpl
description: Portfolio and brain dump for kevin cunanan chappelle, creator of multimedia projects and performances. Based in New York City.

url: "https://kvnchpl.github.io"
baseurl: ""

permalink: /:collection/:name/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - .gitignore
  - .gitattributes
  - private
  - _site